[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "proj-sketches"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "Pablo García Mezcua"}]
license = "MIT"
license-files = ["LICENSE"]

[project.optional-dependencies]
dev = ["pytest>=8"]

[tool.setuptools.packages.find]
where = ["src"]